// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"strconv"
	"strings"
	"time"
)

func main() {
	fs, _ := ioutil.ReadDir(".")
	out, _ := os.Create("static_generated.go")

	out.Write([]byte("// Code generated by generate_static.go; DO NOT EDIT.\n\npackage static\n\n"))
	out.Write([]byte("import \"time\"\n\n"))

	now := time.Now()
	out.Write([]byte("var ModTime = time.Unix("))
	out.Write([]byte(fmt.Sprintf("%d, %d", 0, now.UnixNano())))
	out.Write([]byte(")\n\n"))

	for _, file := range fs {
		filename := file.Name()
		if strings.HasPrefix(filename, ".") || strings.HasSuffix(filename, ".go") {
			continue
		}
		content, err := ioutil.ReadFile(filename)
		if err != nil {
			panic(err)
		}
		parts := strings.Split(filename, ".")
		parts = append(strings.Split(parts[0], "_"), parts[1:]...)
		for i := range parts {
			parts[i] = strings.Title(parts[i])
		}
		basename := strings.Join(parts, "")

		out.Write([]byte("const "))
		out.Write([]byte(strings.Title(basename)))
		out.Write([]byte(" = "))
		out.Write([]byte(strconv.Quote(string(content))))
		out.Write([]byte("\n"))
	}
}
